"""add ticket fields to event and ticket_purchases table

Revision ID: 3f1f02e3fdd3
Revises: cfc277a555c7
Create Date: 2026-05-28 17:32:21.747655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1f02e3fdd3'
down_revision: Union[str, None] = 'cfc277a555c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('buyer_email', sa.String(), nullable=False),
    sa.Column('buyer_phone', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_ticket_purchases_id'), 'ticket_purchases', ['id'], unique=False)
    op.add_column('events', sa.Column('ticket_price', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('tickets_available', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'tickets_available')
    op.drop_column('events', 'ticket_price')
    op.drop_index(op.f('ix_ticket_purchases_id'), table_name='ticket_purchases')
    op.drop_table('ticket_purchases')
    # ### end Alembic commands ###
