"""add verification_channel to users

Revision ID: 77cc140053c0
Revises: f49d174ead38
Create Date: 2026-05-28 19:18:18.710128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cc140053c0'
down_revision: Union[str, None] = 'f49d174ead38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_channel')
    # ### end Alembic commands ###
