"""add rsvp_token to guests

Revision ID: cfc277a555c7
Revises: 1b39690bb15f
Create Date: 2026-05-28 17:27:01.688981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc277a555c7'
down_revision: Union[str, None] = '1b39690bb15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('rsvp_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_guests_rsvp_token'), 'guests', ['rsvp_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guests_rsvp_token'), table_name='guests')
    op.drop_column('guests', 'rsvp_token')
    # ### end Alembic commands ###
