"""add timezone to events

Revision ID: f49d174ead38
Revises: ccb9f677f97f
Create Date: 2026-05-28 19:11:21.672609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49d174ead38'
down_revision: Union[str, None] = 'ccb9f677f97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'timezone')
    # ### end Alembic commands ###
